# Generated by Skyramp v1.3.24 on 2026-05-25 08:40:32.747614535 +0000 UTC m=+596.611514114
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output cancel_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cancel-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    endpoint_2_POST_request_body = '{"name": "test-flow-cancel-' + str(int(time.time())) + '"}'

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert len(str(skyramp.get_response_value(endpoint_2_POST_response, "id"))) == 36
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = '{"flow_id": "' + flow_id + '", "name": "test-flow-run-cancel", "state": {"name": "Scheduled", "type": "SCHEDULED"}}'

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "flow_id") == flow_id
    assert skyramp.get_response_value(endpoint_1_POST_response, "state_type") == "SCHEDULED"
    assert len(str(skyramp.get_response_value(endpoint_1_POST_response, "id"))) == 36
    flow_run_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "TestBot cancellation test"
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{id}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        path_params={"id": flow_run_id}
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "id") == flow_run_id
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "TestBot cancellation test"


if __name__ == "__main__":
    test_integration()
