# Generated by Skyramp v1.3.21 on 2026-05-18 08:26:53.93157576 +0000 UTC m=+334.354254288
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output cancel_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cancel_post_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    flow_runs = "2"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-cancel-flow-1"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "test-cancel-flow-1"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = f'{{"flow_id": "{flow_id}"}}'
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    flow_runs = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by user."
    }'''
    
    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        path_params={"flow_runs": flow_runs}
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "Cancelled by user."
    assert skyramp.get_response_value(cancel_POST_response, "id") is not None


if __name__ == "__main__":
    test_integration()
