# Generated by Skyramp v1.3.19 on 2026-04-20 17:47:41.668109105 +0000 UTC m=+339.813854890
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output cancel_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cancel-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-1745000000"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None

    # Request Body
    endpoint_1_POST_request_body = '{"flow_id": "' + str(skyramp.get_response_value(endpoint_2_POST_response, "id")) + '", "name": "test-run-1745000000"}'

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Declaration of variables
    flow_runs = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Test cancellation"
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        path_params={"flow_runs": flow_runs}
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "id") is not None
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "Test cancellation"


if __name__ == "__main__":
    test_integration()
