# Generated by Skyramp v1.3.24 on 2026-05-25 08:40:27.163165151 +0000 UTC m=+591.027064720
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_cancel_flow_run_422_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=not-a-valid-uuid \
# 		--provider \
# 		--request-data {"reason":"test cancellation"} \
# 		--response-status-code 422 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "not-a-valid-uuid"

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "test cancellation"
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert cancel_POST_response.status_code == 422
    assert skyramp.get_response_value(cancel_POST_response, "detail") is not None
    assert skyramp.get_response_value(cancel_POST_response, "detail.0.loc.0") == "path"
    assert skyramp.get_response_value(cancel_POST_response, "detail.0.loc.1") == "id"
    assert skyramp.get_response_value(cancel_POST_response, "detail.1") is None


if __name__ == "__main__":
    test_cancel_post()
