# Generated by Skyramp v1.3.21 on 2026-05-18 08:40:15.363012236 +0000 UTC m=+331.731339251
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_flow_run_retry_200_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"reason":"Manual retry by user","parameters":{}} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a3f8c2d1-4b5e-4f6a-8c9b-1e2d3f4a5b6c"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Manual retry by user"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Manual retry by user"
    assert skyramp.get_response_value(retry_POST_response, "id") == "a3f8c2d1-4b5e-4f6a-8c9b-1e2d3f4a5b6c"


if __name__ == "__main__":
    test_retry_post()
