# Generated by Skyramp v1.3.21 on 2026-05-18 08:39:57.473617335 +0000 UTC m=+313.841944360
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_flow_run_retry_422_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=not-a-valid-uuid \
# 		--provider \
# 		--request-data {"reason":"Retry test"} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "not-a-valid-uuid"

    # Request Body
    retry_POST_request_body = r'''{
        "reason": "Retry test"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert retry_POST_response.status_code == 422
    assert skyramp.get_response_value(retry_POST_response, "detail") is not None
    assert len(skyramp.get_response_value(retry_POST_response, "detail")) >= 1
    assert skyramp.get_response_value(retry_POST_response, "detail.0.type") == "uuid_parsing"
    assert skyramp.get_response_value(retry_POST_response, "detail.0.input") == "not-a-valid-uuid"
    assert skyramp.get_response_value(retry_POST_response, "detail.0.loc.1") == "id"


if __name__ == "__main__":
    test_retry_post()
