# Generated by Skyramp v1.3.24 on 2026-05-25 08:40:30.512872946 +0000 UTC m=+594.376772525
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_cancel_flow_run_200_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"reason":"Cancelled by TestBot."} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by TestBot."
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "Cancelled by TestBot."
    id_val = skyramp.get_response_value(cancel_POST_response, "id")
    assert id_val is not None
    assert len(str(id_val)) == 36
    assert str(id_val).count('-') == 4


if __name__ == "__main__":
    test_cancel_post()
