# Generated by Skyramp v1.3.21 on 2026-05-04 08:20:58.990243643 +0000 UTC m=+460.885988690
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_run_retry_200_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"parameters":{},"reason":"Test retry"} \
# 		--response-data {"id":"c9b1a2d3-e4f5-6789-bcde-f01234567891","state":"SCHEDULED","message":"Test retry"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "c9b1a2d3-e4f5-6789-bcde-f01234567891"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Test retry"
    }'''

    # Expected Response Body
    expected_retry_POST_response_body = r'''{
        "id": "c9b1a2d3-e4f5-6789-bcde-f01234567891",
        "message": "Test retry",
        "state": "SCHEDULED"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.check_schema(retry_POST_response, expected_retry_POST_response_body)
    assert skyramp.get_response_value(retry_POST_response, "id") is not None
    assert skyramp.get_response_value(retry_POST_response, "message") == "Test retry"
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"


if __name__ == "__main__":
    test_retry_post()
