# Generated by Skyramp v1.3.19 on 2026-04-20 17:47:34.013654341 +0000 UTC m=+332.159400136
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_run_cancel_200_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=550e8400-e29b-41d4-a716-446655440099 \
# 		--provider \
# 		--request-data {"reason":"Cancelled by user."} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "550e8400-e29b-41d4-a716-446655440099"

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by user."
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "id") is not None
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "Cancelled by user."


if __name__ == "__main__":
    test_cancel_post()
