# Generated by Skyramp v1.3.19 on 2026-04-20 17:59:14.684600384 +0000 UTC m=+234.584374575
# Command: skyramp generate contract rest http://localhost:4200/flow_runs/{id}/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_run_retry_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=c4d5e6f7-a8b9-0123-cdef-456789abcdef \
# 		--provider \
# 		--request-data {"reason":"Retried by user.","parameters":{}} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /flow_runs/{id}/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "c4d5e6f7-a8b9-0123-cdef-456789abcdef"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retried by user."
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/flow_runs/{id}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "id") is not None
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Retried by user."


if __name__ == "__main__":
    test_retry_post()
