# Generated by Skyramp v1.3.13 on 2026-03-18 14:18:36.774545184 +0000 UTC m=+195.066486238
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output fuzz_test_flow_run_cancel.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"reason":"Cancelled by user."} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow_runs/00000000-0000-0000-0000-000000000001/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    cancel_POST_request_body = r'''{
      "reason": "Cancelled by user."
    }'''
    
    # Fuzz strategies
    cancel_post_fuzzed_body = {"reason": "0123456789"}
    # Fuzz status codes
    expected_cancel_post_status_code = {"reason": "40x"}
    # Fuzz status codes for Null values
    expected_cancel_post_null_status_code = {"reason": "40x"}

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(cancel_post_fuzzed_body):
        # Execute Request
        cancel_POST_response = client.send_request(
            url=URL,
            path="/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel",
            method="POST",
            body=cancel_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(cancel_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_cancel_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(cancel_post_fuzzed_body, key) }'
        )

        # Execute Request
        cancel_POST_response = client.send_request(
            url=URL,
            path="/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel",
            method="POST",
            body=cancel_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_cancel_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_cancel_post()
