# Generated by Skyramp v1.3.16 on 2026-03-30 07:34:33.765238828 +0000 UTC m=+146.015268102
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output integration_cancel_flow_run_happy_path.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_cancel-flow-run-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "c3d4e5f6-a7b8-9012-cdef-012345678902"

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by user."
    }'''
    
    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        path_params={"flow_runs": flow_runs}
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 200
    assert skyramp.get_response_value(cancel_POST_response, "id") is not None
    assert skyramp.get_response_value(cancel_POST_response, "state") == "CANCELLING"
    assert skyramp.get_response_value(cancel_POST_response, "message") == "Cancelled by user."


if __name__ == "__main__":
    test_integration()
