# Generated by Skyramp v1.3.19 on 2026-04-20 17:59:31.209323852 +0000 UTC m=+251.109098063
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output retry_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_retry-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "b1c2d3e4-f5a6-7890-abcd-ef1234567890"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retried by user."
    }'''
    
    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/{flow_runs}/retry",
        method="POST",
        body=retry_POST_request_body,
        path_params={"flow_runs": flow_runs}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "id") is not None
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Retried by user."


if __name__ == "__main__":
    test_integration()
