# Generated by Skyramp v1.3.21 on 2026-05-18 08:40:12.479555758 +0000 UTC m=+328.847882794
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output retry_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_retry-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    flow_runs = "1"

    # Request Body
    flows_POST_request_body = r'''{
        "name": "test-flow-1748000000"
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 200
    assert skyramp.get_response_value(flows_POST_response, "name") == "test-flow-1748000000"
    assert skyramp.get_response_value(flows_POST_response, "id") is not None

    # Request Body
    flow_runs_POST_request_body = r'''{
        "flow_id": "1",
        "name": "test-run-1748000000",
        "state": {
            "message": "Test failure",
            "type": "FAILED"
        }
    }'''
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=flow_runs_POST_request_body,
        data_override={"flow_id": flow_runs}
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201
    assert skyramp.get_response_value(flow_runs_POST_response, "name") == "test-run-1748000000"
    assert skyramp.get_response_value(flow_runs_POST_response, "id") is not None
    assert skyramp.get_response_value(flow_runs_POST_response, "state_type") == "FAILED"

    # Request Body
    retry_POST_request_body = r'''{
        "reason": "Manual retry for testing"
    }'''
    
    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/retry",
        method="POST",
        body=retry_POST_request_body,
        path_params={"flow_runs": flow_runs}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Manual retry for testing"
    assert skyramp.get_response_value(retry_POST_response, "id") is not None


if __name__ == "__main__":
    test_integration()
