# Generated by Skyramp v1.3.21 on 2026-05-04 08:21:06.945861498 +0000 UTC m=+468.841606555
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output retry_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_retry-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    flows_POST_request_body = r'''{
        "name": "test-flow-1714000000"
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=flows_POST_request_body
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.get_response_value(flows_POST_response, "name") == "test-flow-1714000000"
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    flow_id = skyramp.get_response_value(flows_POST_response, "id")

    # Request Body
    flow_runs_POST_request_body = '{"flow_id": "' + str(flow_id) + '", "name": "test-run-1714000000"}'

    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=flow_runs_POST_request_body
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201
    assert skyramp.get_response_value(flow_runs_POST_response, "name") == "test-run-1714000000"
    assert skyramp.get_response_value(flow_runs_POST_response, "flow_id") == flow_id
    assert skyramp.get_response_value(flow_runs_POST_response, "id") is not None
    flow_run_id = skyramp.get_response_value(flow_runs_POST_response, "id")

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "message": "Intentional test failure",
            "type": "FAILED"
        }
    }'''

    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        path_params={"flow_runs": flow_run_id}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 200
    assert skyramp.get_response_value(set_state_POST_response, "state.type") == "FAILED"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Test retry after failure"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/retry",
        method="POST",
        body=retry_POST_request_body,
        path_params={"flow_runs": flow_run_id}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Test retry after failure"
    assert skyramp.get_response_value(retry_POST_response, "id") == flow_run_id


if __name__ == "__main__":
    test_integration()
