# Generated by Skyramp v1.3.13 on 2026-03-18 04:22:12.092623024 +0000 UTC m=+107.659983342
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_retry_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-retry-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "name": "test-retry-flow",
        "tags": [
            "retry-test"
        ]
    }'''
    
    # Execute Request
    flows_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flows_POST_response.status_code == 200

    # Request Body
    flow_runs_POST_request_body = '{{"flow_id": "{}", "name": "test-retry-flow-run", "parameters": {{"key": "value"}}, "state": {{"type": "SCHEDULED"}}}}'.format(
        skyramp.get_response_value(flows_POST_response, "id")
    )
    
    # Execute Request
    flow_runs_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs",
        method="POST",
        body=flow_runs_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert flow_runs_POST_response.status_code == 201

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "message": "Simulated failure for retry test",
            "type": "FAILED"
        }
    }'''
    
    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(flow_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 201

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {
            "key": "overridden_value"
        },
        "reason": "Retried by test"
    }'''
    
    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(flow_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200

    # Execute Request
    flow_runs_flow_runs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}",
        method="GET",
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(flow_runs_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_runs_flow_runs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
