# Generated by Skyramp v1.3.11 on 2026-03-11 18:53:12.051988717 +0000 UTC m=+222.108055743
# Command: skyramp generate contract rest http://localhost:4200/api/flows/00000000-0000-0000-0000-000000000000/run-stats \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_run_stats_404.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:4200"

# contract test for /api/flows/00000000-0000-0000-0000-000000000000/run-stats GET
def test_run_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    run_stats_GET_response = client.send_request(
        url=URL,
        path="/api/flows/00000000-0000-0000-0000-000000000000/run-stats",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert run_stats_GET_response.status_code == 404

if __name__ == "__main__":
    test_run_stats_get()
