# Generated by Skyramp v1.3.13 on 2026-03-18 04:15:30.705441211 +0000 UTC m=+175.651699541
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_run_cancel_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"reason":"Cancelled by user."} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/flow_runs/00000000-0000-0000-0000-000000000001/cancel POST
def test_cancel_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by user."
    }'''

    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/00000000-0000-0000-0000-000000000001/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert cancel_POST_response.status_code == 200


if __name__ == "__main__":
    test_cancel_post()
