# Generated by Skyramp v1.3.13 on 2026-03-18 14:25:56.250945127 +0000 UTC m=+153.625932848
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/22222222-2222-2222-2222-222222222222/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_run_retry_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"parameters":{},"reason":"Retried by user."} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/22222222-2222-2222-2222-222222222222/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retried by user."
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/22222222-2222-2222-2222-222222222222/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(retry_POST_response, "20x")


if __name__ == "__main__":
    test_retry_post()
