# Generated by Skyramp v1.3.13 on 2026-03-18 04:22:55.96431893 +0000 UTC m=+151.531679238
# Command: skyramp generate fuzz rest http://localhost:4200/api/flow_runs/00000000-0000-0000-0000-000000000000/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_run_retry_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"parameters":{},"reason":"Retried by user."} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# fuzz test for /api/flow_runs/00000000-0000-0000-0000-000000000000/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    retry_POST_request_body = r'''{
      "parameters": {},
      "reason": "Retried by user."
    }'''
    
    # Fuzz strategies
    retry_post_fuzzed_body = {
        "parameters": {},
        "reason": "0123456789"
    }
    # Fuzz status codes
    expected_retry_post_status_code = {
        "parameters": "40x",
        "reason": "40x"
    }
    # Fuzz status codes for Null values
    expected_retry_post_null_status_code = {
        "parameters": "40x",
        "reason": "40x"
    }

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/00000000-0000-0000-0000-000000000000/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(retry_post_fuzzed_body):
        # Execute Request
        retry_POST_response = client.send_request(
            url=URL,
            path="/api/flow_runs/00000000-0000-0000-0000-000000000000/retry",
            method="POST",
            body=retry_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(retry_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_retry_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(retry_post_fuzzed_body, key) }'
        )

        # Execute Request
        retry_POST_response = client.send_request(
            url=URL,
            path="/api/flow_runs/00000000-0000-0000-0000-000000000000/retry",
            method="POST",
            body=retry_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_retry_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_retry_post()
