# Generated by Skyramp v1.3.13 on 2026-03-18 04:14:53.283224318 +0000 UTC m=+138.229482659
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_cancel_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-cancel-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-cancel-flow-001"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    _flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")
    endpoint_1_POST_request_body = f'''{{
        "flow_id": "{_flow_id}",
        "name": "test-cancel-run-001",
        "state": {{
            "message": "Scheduled for testing",
            "type": "SCHEDULED"
        }}
    }}'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    cancel_POST_request_body = r'''{
        "reason": "Cancelled by test"
    }'''
    
    # Execute Request
    cancel_POST_response = client.send_request(
        url=URL_,
        path="/api/flow_runs/{flow_runs}/cancel",
        method="POST",
        body=cancel_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert cancel_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
