# Generated by Skyramp v1.3.13 on 2026-03-18 14:25:26.80092565 +0000 UTC m=+124.175913331
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_retry_integration.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-retry-integration.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "retry-test-flow"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{{"flow_id": "{flow_id}", "name": "retry-test-run"}}'.format(
        flow_id=skyramp.get_response_value(endpoint_2_POST_response, "id")
    )
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "message": "Simulated failure for retry test",
            "type": "FAILED"
        }
    }'''
    
    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 200

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retried by user."
    }'''
    
    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
