# Generated by Skyramp v1.3.11 on 2026-03-11 18:52:32.416814957 +0000 UTC m=+182.472881974
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_stats_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-run-stats-lifecycle.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:4200"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "stats-test-flow",
        "tags": [
            "test"
        ]
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Dynamic chaining: capture flow ID from POST response
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "flow_id": "11111111-1111-1111-1111-111111111111",
        "name": "completed-run",
        "state": {
            "name": "Completed",
            "type": "COMPLETED"
        }
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        data_override={"flow_id": flow_id}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "flow_id": "11111111-1111-1111-1111-111111111111",
        "name": "failed-run",
        "state": {
            "message": "Task failed",
            "name": "Failed",
            "type": "FAILED"
        }
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/flow_runs/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        data_override={"flow_id": flow_id}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Execute Request
    run_stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/flows/{flows}/run-stats",
        method="GET",
        path_params={"flows": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert run_stats_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
