# Generated by Skyramp v1.3.24 on 2026-05-25 08:57:28.534181637 +0000 UTC m=+506.604568816
# Command: skyramp generate contract rest http://localhost:4200/api/flow_runs/{id}/retry \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output flow_run_retry_success_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests/skyramp \
# 		--overwrite \
# 		--path-params id=b5c6d7e8-f9a0-1234-5678-90abcdef1234 \
# 		--provider \
# 		--request-data {"reason":"Retry after failure","parameters":{}} \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow_runs/{id}/retry POST
def test_retry_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "b5c6d7e8-f9a0-1234-5678-90abcdef1234"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retry after failure"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL,
        path="/api/flow_runs/{id}/retry",
        method="POST",
        body=retry_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert retry_POST_response.status_code == 404
    assert skyramp.get_response_value(retry_POST_response, "detail") == "Flow run b5c6d7e8-f9a0-1234-5678-90abcdef1234 not found."


if __name__ == "__main__":
    test_retry_post()
