# Generated by Skyramp v1.3.24 on 2026-05-25 08:57:31.510796056 +0000 UTC m=+509.581183245
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output retry_post_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/skyramp/scenario_retry-post-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    ts = int(time.time())

    # Request Body
    endpoint_2_POST_request_body = f'{{"name": "retry-test-flow-{ts}"}}'

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == f"retry-test-flow-{ts}"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_1_POST_request_body = f'{{"flow_id": "{flow_id}", "name": "retry-test-run-{ts}"}}'

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == f"retry-test-run-{ts}"
    assert skyramp.get_response_value(endpoint_1_POST_response, "flow_id") == flow_id
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    flow_run_id = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "message": "Intentional failure for retry test",
            "type": "FAILED"
        }
    }'''

    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_run_id}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        path_params={"flow_run_id": flow_run_id}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 201
    assert skyramp.get_response_value(set_state_POST_response, "status") == "ACCEPT"

    # Request Body
    retry_POST_request_body = r'''{
        "parameters": {},
        "reason": "Retry test"
    }'''

    # Execute Request
    retry_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_run_id}/retry",
        method="POST",
        body=retry_POST_request_body,
        path_params={"flow_run_id": flow_run_id}
    )
    # Generated Assertions
    assert retry_POST_response.status_code == 200
    assert skyramp.get_response_value(retry_POST_response, "id") == flow_run_id
    assert skyramp.get_response_value(retry_POST_response, "state") == "SCHEDULED"
    assert skyramp.get_response_value(retry_POST_response, "message") == "Retry test"


if __name__ == "__main__":
    test_integration()
